class Pair < ActiveHash::Base
  self.data = [
    
    { id: 1, name: '--' },
    { id: 2, name: 'AUD/CAD' },
    { id: 3, name: 'AUD/GBP' },
    { id: 4, name: 'AUD/JPY' },
    { id: 5, name: 'AUD/NZD' },
    { id: 6, name: 'AUD/USD' },
    { id: 7, name: 'CAD/CHF' },
    { id: 8, name: 'CAD/JPY' },
    { id: 9, name: 'CHF/JPY' },
    { id: 10, name: 'EUR/AUD' },
    { id: 11, name: 'EUR/CAD' },
    { id: 12, name: 'EUR/CHF' },
    { id: 13, name: 'EUR/GBP' },
    { id: 14, name: 'EUR/JPY' },
    { id: 15, name: 'EUR/NZD' },
    { id: 16, name: 'EUR/USD' },
    { id: 17, name: 'GBP/AUD' },
    { id: 18, name: 'GBP/CAD' },
    { id: 19, name: 'GBP/CHF' },
    { id: 20, name: 'GBP/JPY' },
    { id: 21, name: 'GBP/NZD' },
    { id: 22, name: 'GBP/USD' },
    { id: 23, name: 'GBP/ZAR' },
    { id: 24, name: 'NZD/CAD' },
    { id: 25, name: 'NZD/JPY' },
    { id: 26, name: 'NZD/USD' },
    { id: 27, name: 'NZD/ZAR' },
    { id: 28, name: 'TRY/JPY' },
    { id: 29, name: 'USD/CAD' },
    { id: 30, name: 'USD/CHF' },
    { id: 31, name: 'USD/ILS' },
    { id: 32, name: 'USD/JPY' },
    { id: 33, name: 'USD/MXN' },
    { id: 34, name: 'USD/TRY' },
    { id: 35, name: 'USD/ZAR' },
    { id: 36, name: 'XAG/AUD' },
    { id: 37, name: 'XAG/EUR' },
    { id: 38, name: 'XAG/GBP' },
    { id: 39, name: 'XAG/USD' },
    { id: 40, name: 'XAU/AUD' },
    { id: 41, name: 'XAU/EUR' },
    { id: 42, name: 'XAU/GBP' },
    { id: 43, name: 'XAU/USD' },
    { id: 44, name: 'XPD/USD' },
    { id: 45, name: 'XPT/USD' },
    { id: 46, name: 'BAT/USD' },
    { id: 47, name: 'BAT/JPY' },
    { id: 48, name: 'SOL/USD' },
    { id: 49, name: 'SOL/JPY' },
    { id: 50, name: 'BTC/JPY' },
    { id: 51, name: 'BTC/USD' },
    { id: 52, name: 'ETH/USD' },
    { id: 53, name: 'ETH/JPY' },
    { id: 54, name: 'LTC/USD' },
    { id: 55, name: 'LTC/JPY' },
    { id: 56, name: 'LUNA/USD' },
    { id: 57, name: 'LUNA/JPY' },
    { id: 58, name: 'MANA/USD' },
    { id: 59, name: 'MANA/JPY' },
    { id: 60, name: 'OMG/USD' },
    { id: 61, name: 'OMG/JPY' },
    { id: 62, name: 'SAND/USD' },
    { id: 63, name: 'SAND/JPY' },
    { id: 64, name: 'XEM/USD' },
    { id: 65, name: 'XEM/JPY' },
    { id: 66, name: 'XLM/USD' },
    { id: 67, name: 'XLM/JPY' },
    { id: 68, name: 'XRP/USD' },
    { id: 69, name: 'XRP/JPY' },
    { id: 70, name: 'XYM/USD' },
    { id: 71, name: 'XYM/JPY' },
    { id: 72, name: 'その他' }
  ]
 
   include ActiveHash::Associations
   has_many :records
 
  end